
# category_choices = {"Snacks" : "Snacks",
#                    "Beverages" : "Beverages",
#                    "Stationary" : "Stationary", 
#                    "Fishing Gear" : "Fishing Gear",
#                    "Cycling Gear" : "Cycling Gear",
#                    "Computer Accessories" : "Computer Accessories",
# }    

brand_choices={
"Nature's Bite":"Nature's Bite",
"ChocoLuxe":"ChocoLuxe",
"CrunchCraft":"CrunchCraft",
"Yogurty's":"Yogurty's",
"Nutty Guys":"Nutty Guys",
"PlantPower":"PlantPower",
"CheeseLovers":"CheeseLovers",
"TeaTime Bakes":"TeaTime Bakes",
"FruitHarvest":"FruitHarvest",
"SnackAttack":"SnackAttack",
"BeanBurst":"BeanBurst",
"FizzFresh":"FizzFresh",
"TeaLeaf":"TeaLeaf",
"ProFuel":"ProFuel",
"TropicalCoco":"TropicalCoco",
"SodaCraft":"SodaCraft",
"GreenLeaf":"GreenLeaf",
"TeaZone":"TeaZone",
"PlantMilk Co.":"PlantMilk Co.",
"PowerUp":"PowerUp",
"WriteWell":"WriteWell",
"ColorPop":"ColorPop",
"NoteIt":"NoteIt",
"Craft & Co":"Craft & Co",
"PreciseWrite":"PreciseWrite",
"CutRight":"CutRight",
"ClipMaster":"ClipMaster",
"Artful":"Artful",
"OrganizeLife":"OrganizeLife",
"StickEase":"StickEase",
"FishMaster":"FishMaster",
"LurePro":"LurePro",
"ReelTech":"ReelTech",
"LineMaster":"LineMaster",
"TacklePro":"TacklePro",
"HookMaster":"HookMaster",
"FishTool":"FishTool",
"FishWear":"FishWear",
"NetPro":"NetPro",
"FloatMaster":"FloatMaster",
"CycleSafe":"CycleSafe",
"GripMaster":"GripMaster",
"LockSecure":"LockSecure",
"LightPro":"LightPro",
"CycleWear":"CycleWear",
"PumpMaster":"PumpMaster",
"RepairPro":"RepairPro",
"CycleFit":"CycleFit",
"BottleHold":"BottleHold",
"CycleTrack":"CycleTrack",
"Meletrix":"Meletrix",
"MousePro":"MousePro",
"HubMaster":"HubMaster",
"SwitchTech":"SwitchTech",
"DeskEase":"DeskEase",
"SoundPro":"SoundPro",
"WristEase":"WristEase",
"DriveFast":"DriveFast",
"PadGlow":"PadGlow",
"CamClear":"CamClear",
"Apple":"Apple",
}

tag_choices = {
    'New' : 'New',
    "Sale" : "Sale",
    "Featured" : "Featured",
    "Limited" : "Limited",
    "Classic" : "Classic"
}