# Generated by Django 5.2.7 on 2025-10-23 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cartitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='session_key',
        ),
    ]
