# Generated by Django 5.2.7 on 2025-10-29 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price_at_order',
            new_name='price',
        ),
    ]
