# Generated by Django 5.2.6 on 2025-10-21 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=1000)),
                ('category_img', models.ImageField(blank=True, default='products/default.jpg', null=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.TextField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('tag', models.CharField(choices=[('New', 'New'), ('Sale', 'Sale'), ('Featured', 'Featured'), ('Limited', 'Limited'), ('Classic', 'Classic')], max_length=20)),
                ('brand', models.CharField(choices=[("Nature's Bite", "Nature's Bite"), ('ChocoLuxe', 'ChocoLuxe'), ('CrunchCraft', 'CrunchCraft'), ("Yogurty's", "Yogurty's"), ('Nutty Guys', 'Nutty Guys'), ('PlantPower', 'PlantPower'), ('CheeseLovers', 'CheeseLovers'), ('TeaTime Bakes', 'TeaTime Bakes'), ('FruitHarvest', 'FruitHarvest'), ('SnackAttack', 'SnackAttack'), ('BeanBurst', 'BeanBurst'), ('FizzFresh', 'FizzFresh'), ('TeaLeaf', 'TeaLeaf'), ('ProFuel', 'ProFuel'), ('TropicalCoco', 'TropicalCoco'), ('SodaCraft', 'SodaCraft'), ('GreenLeaf', 'GreenLeaf'), ('TeaZone', 'TeaZone'), ('PlantMilk Co.', 'PlantMilk Co.'), ('PowerUp', 'PowerUp'), ('WriteWell', 'WriteWell'), ('ColorPop', 'ColorPop'), ('NoteIt', 'NoteIt'), ('Craft & Co', 'Craft & Co'), ('PreciseWrite', 'PreciseWrite'), ('CutRight', 'CutRight'), ('ClipMaster', 'ClipMaster'), ('Artful', 'Artful'), ('OrganizeLife', 'OrganizeLife'), ('StickEase', 'StickEase'), ('FishMaster', 'FishMaster'), ('LurePro', 'LurePro'), ('ReelTech', 'ReelTech'), ('LineMaster', 'LineMaster'), ('TacklePro', 'TacklePro'), ('HookMaster', 'HookMaster'), ('FishTool', 'FishTool'), ('FishWear', 'FishWear'), ('NetPro', 'NetPro'), ('FloatMaster', 'FloatMaster'), ('CycleSafe', 'CycleSafe'), ('GripMaster', 'GripMaster'), ('LockSecure', 'LockSecure'), ('LightPro', 'LightPro'), ('CycleWear', 'CycleWear'), ('PumpMaster', 'PumpMaster'), ('RepairPro', 'RepairPro'), ('CycleFit', 'CycleFit'), ('BottleHold', 'BottleHold'), ('CycleTrack', 'CycleTrack'), ('Meletrix', 'Meletrix'), ('MousePro', 'MousePro'), ('HubMaster', 'HubMaster'), ('SwitchTech', 'SwitchTech'), ('DeskEase', 'DeskEase'), ('SoundPro', 'SoundPro'), ('WristEase', 'WristEase'), ('DriveFast', 'DriveFast'), ('PadGlow', 'PadGlow'), ('CamClear', 'CamClear')], max_length=20)),
                ('product_img', models.ImageField(blank=True, default='products/default.jpg', null=True, upload_to='photos/%Y/%m/%d/')),
                ('product_img1', models.ImageField(blank=True, default='products/default.jpg', null=True, upload_to='photos/%Y/%m/%d/')),
                ('product_img2', models.ImageField(blank=True, default='products/default.jpg', null=True, upload_to='photos/%Y/%m/%d/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
