# Generated by Django 5.2.6 on 2025-10-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[("Nature's Bite", "Nature's Bite"), ('ChocoLuxe', 'ChocoLuxe'), ('CrunchCraft', 'CrunchCraft'), ("Yogurty's", "Yogurty's"), ('Nutty Guys', 'Nutty Guys'), ('PlantPower', 'PlantPower'), ('CheeseLovers', 'CheeseLovers'), ('TeaTime Bakes', 'TeaTime Bakes'), ('FruitHarvest', 'FruitHarvest'), ('SnackAttack', 'SnackAttack'), ('BeanBurst', 'BeanBurst'), ('FizzFresh', 'FizzFresh'), ('TeaLeaf', 'TeaLeaf'), ('ProFuel', 'ProFuel'), ('TropicalCoco', 'TropicalCoco'), ('SodaCraft', 'SodaCraft'), ('GreenLeaf', 'GreenLeaf'), ('TeaZone', 'TeaZone'), ('PlantMilk Co.', 'PlantMilk Co.'), ('PowerUp', 'PowerUp'), ('WriteWell', 'WriteWell'), ('ColorPop', 'ColorPop'), ('NoteIt', 'NoteIt'), ('Craft & Co', 'Craft & Co'), ('PreciseWrite', 'PreciseWrite'), ('CutRight', 'CutRight'), ('ClipMaster', 'ClipMaster'), ('Artful', 'Artful'), ('OrganizeLife', 'OrganizeLife'), ('StickEase', 'StickEase'), ('FishMaster', 'FishMaster'), ('LurePro', 'LurePro'), ('ReelTech', 'ReelTech'), ('LineMaster', 'LineMaster'), ('TacklePro', 'TacklePro'), ('HookMaster', 'HookMaster'), ('FishTool', 'FishTool'), ('FishWear', 'FishWear'), ('NetPro', 'NetPro'), ('FloatMaster', 'FloatMaster'), ('CycleSafe', 'CycleSafe'), ('GripMaster', 'GripMaster'), ('LockSecure', 'LockSecure'), ('LightPro', 'LightPro'), ('CycleWear', 'CycleWear'), ('PumpMaster', 'PumpMaster'), ('RepairPro', 'RepairPro'), ('CycleFit', 'CycleFit'), ('BottleHold', 'BottleHold'), ('CycleTrack', 'CycleTrack'), ('Meletrix', 'Meletrix'), ('MousePro', 'MousePro'), ('HubMaster', 'HubMaster'), ('SwitchTech', 'SwitchTech'), ('DeskEase', 'DeskEase'), ('SoundPro', 'SoundPro'), ('WristEase', 'WristEase'), ('DriveFast', 'DriveFast'), ('PadGlow', 'PadGlow'), ('CamClear', 'CamClear'), ('Apple', 'Apple')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True, default='static/img/default.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img1',
            field=models.ImageField(blank=True, default='static/img/default.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img2',
            field=models.ImageField(blank=True, default='static/img/default.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
