# Generated by Django 5.2.6 on 2025-10-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_product_img_alter_product_product_img1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True, default='products/default.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
