# Generated by Django 5.2.6 on 2025-10-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_category_category_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_img',
            field=models.ImageField(blank=True, default='/static/img/default.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True, default='/static/img/default.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img1',
            field=models.ImageField(blank=True, default='/static/img/default.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img2',
            field=models.ImageField(blank=True, default='/static/img/default.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
